stages:
  - build
  - deploy

build iti0302-2023-backend:
  stage: build
  only:
    refs:
      - main
  tags:
    - main

  script:
    - ./mvnw package
    - docker build -t iti0302-2023-backend .

deploy iti0302-2023-backend:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - main
  script:
    - cd /opt/iti0302-2023-backend
    - docker-compose down
    - docker-compose up -d